### PR TITLE
Separate commit hashes with space instead of comma

### LINKED ISSUE #22: cherry-pick command from comment fails because of separator
> \# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick be98866b3e5ee42b5a6e1d5ebb93a24ff2327c95,cf5891e73a7f572f79d963932073a373e31a6ff5,199400fb069e31b377f8ce52b8c7c1fd8bea30a2

Should this not be space separated instead of comma? Because trying the suggestion I got
>fatal: bad revision 'be98866b3e5ee42b5a6e1d5ebb93a24ff2327c95,cf5891e73a7f572f79d963932073a373e31a6ff5,199400fb069e31b377f8ce52b8c7c1fd8bea30a2'

Without the comma, it made it.

_Originally posted by @DelazJ in https://github.com/qgis/QGIS-Documentation/issues/7629#issuecomment-1158684354_

### PR DESCRIPTION
**Pull request by faebebin**
fix #22

### CODE REVIEW

**Comment by faebebin** [comment]
@m-kuhn habs nicht ausprobiert. Nur schnell hier auf github web editor reingschrieben :).

**Comment by m-kuhn** [comment]
Danke @faebebin , das sieht gut aus

**Comment by agiudiceandrea** [comment]
Hi @m-kuhn, it looks like this patch isn't used by the qgis-bot. Do you know why?

**Comment by m-kuhn** [comment]
It was never released, qgis uses the latest release... https://github.com/qgis/QGIS/blob/master/.github/workflows/backport.yml#L16

**Comment by agiudiceandrea** [comment]
Do you plan to release a new version soon or do you think it's better that the QGIS repository don't use the current latest release?

**Comment by m-kuhn** [comment]
I could release a new version. Ideally we'd also integrate the changes that happened on tibdex/backport meanwhile, but they are non trivial.
At the same time I wonder if e.g. https://github.com/sqren/backport-github-action could completely replace this?

**Pull request merged**
